[package]
name = "broker_protos"
version = "0.1.0"
authors = ["Ricardo Delfin <me@rdelfin.com>"]
edition = "2018"

[dependencies]
prost = "0.7"
tonic = "0.4"

[build-dependencies]
tonic-build = "0.4"
